### ISSUE TITLE
Fix link to Adam Bien's blog

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartablogs.ee#38] opened 2019-02-21 12:47 UTC
Adam Bien's blog link is currently: http://adambien.blog/roller, please change it to http://adambien.blog/

**Comment by chrisguindon** [comment] 2019-02-26 21:20
The problem is with the author rss feed:
view-source:http://adambien.blog/roller/abien/feed/entries/rss

 <link>http://adambien.blog/roller</link>

The website is using the link value for the link to the blog!

**Comment by chrisguindon** [comment] 2019-02-26 21:22
Closing since this is a dup of #36

**Closed by chrisguindon** 2019-02-26 21:22 UTC
