### ISSUE TITLE
More than two blog posts are showing for some feeds

### ISSUE THREAD

**Issue by lauracowen** [jakartaee/jakartablogs.ee#110] opened 2023-05-26 09:38 UTC
**Describe the bug**
Some, but not all, blogs in the [Jakarta EE blog aggregator](https://jakarta.ee/blogs/) are displaying more than two posts.

The project is, however, configured to only show 2 posts per author (per submitted feed?):
[https://github.com/jakartaee/jakartablogs.ee/blob/master/planet/planet.ini#L22](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jakartaee_jakartablogs.ee_blob_master_planet_planet.ini-23L22&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=gcyYPtqPFX2NiQMciqLq8xULGO0BrAsOljezg3oOO8g&m=ROGzjzvaRn_SpCQErwqyo62gBzs9bCPBr-HJG6xxXGjwAdVKX-xoJhOZu9cfPHpo&s=G-cGlICH1swu-a3-rRK1F6qLva732VrK7DDPl8JnyVo&e=)
(confirmed intended current behaviour with @chrisguindon)

**To Reproduce**
1. Go to [Jakarta EE blog aggregator](https://jakarta.ee/blogs/).
2. Scroll down to (for example) entries from the Francesco Marchioni blog.
3. See there are more than two entries from that blog.

**Expected behavior**
Only two posts per author. For example, Reza's posts or Open Liberty's posts (each post's title is prefixed with the author's name).

**Screenshots**
![image](https://github.com/jakartaee/jakartablogs.ee/assets/3322532/48a4bec6-5d51-4333-8e6d-3b51d372ea6f)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Additional context**

**Comment by chrisguindon** [comment] 2023-05-29 13:20
@autumnfound Can you or @ZacharySabourin take a look at this? I did spend some time on this last week and I was not able to find a reason why we are seeing more than 2 posts from the Francesco Marchioni blog.

**Comment by oliviergoulet5** [comment] 2024-10-11 18:58
This bug is still present.

**Comment by chrisguindon** [comment] 2024-10-11 19:22
This is a weird problem but an observation is that currently, the duplication is with the first post on the page. Interestingly enough, the body of the post is different but it's the same article.

As far as I know, we don't have this problem with planeteclipse.org, so I am taking a chance and compared the configs with that site and made an MR to add things that I noticed were missing: https://github.com/jakartaee/jakartablogs.ee/pull/115

**Comment by chrisguindon** [comment] 2024-10-11 19:31
Looks like my MR did the trick. The duplicated blog post is now gone after the rebuild.

Closing this issue! Thanks @oliviergoulet5 for bringing this issue back to our attention.

**Comment by lauracowen** [comment] 2024-10-16 08:54
@chrisguindon I still see more than two entries from a single blog feed. I know Francesco's blog seems to have multiple feeds set up (I guess that's intentional) but I still see at least three from a single URL prefix (which I assume is a single feed?):

https://www.mastertheboss.com/java-ee/jakarta-ee/simplifying-to-migration-to-jakarta-ee-with-tools/
https://www.mastertheboss.com/java-ee/jakarta-ee/consuming-jakarta-ee-rest-services-with-react/
https://www.mastertheboss.com/java-ee/jakarta-ee/getting-started-with-jakarta-rest-services-4-0/

**Comment by chrisguindon** [comment] 2024-10-16 13:06
> I still see more than two entries from a single blog feed. I know Francesco's blog seems to have multiple feeds set up (I guess that's intentional) but I still see at least three from a single URL prefix (which I assume is a single feed?):

As far as I can tell, Francesco only has 1 feed listed with us:
https://github.com/jakartaee/jakartablogs.ee/blob/master/planet/planet.ini#L204

I can see that all of his posts are making their way to this site. However, the site is configured to only show two posts from each feed: https://github.com/jakartaee/jakartablogs.ee/blob/master/planet/planet.ini#L25

Docs:
http://intertwingly.net/code/venus/docs/config.html

```
new_feed_items
Maximum number of items to include in the output from any one feed
```

**Comment by chrisguindon** [comment] 2024-10-16 13:25
I suspect the issue might be related to Francesco's RSS feed not passing validation:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.mastertheboss.com%2Ffeed%2F%3Fcat%3D108%2C110

@fmarchioni - Would you be able to address the validation errors? I am hoping It might resolve the issue we're facing.

Currently, all your blog posts are showing on our site, even though it's configured to display only 2 per feed. I’ve tried a few solutions on my end, but haven’t had any success so far.

- https://github.com/jakartaee/jakartablogs.ee/commit/bd86bf4a9f7b0af8a8c9f829f4a648a722fe4efc
- https://github.com/jakartaee/jakartablogs.ee/commit/5793d707d9bc0d04c93c620a8d47982b005bc816

**Comment by chrisguindon** [comment] 2024-10-16 13:37
I pushed another commit this morning to start using:

> cache_keep_entries
> Used by expunge to determine how many entries should be kept for each source when expunging old entries from the cache directory. This may be overriden on a per subscription feed basis.

I am hoping that setting this to 2 may help with this issue.

https://github.com/jakartaee/jakartablogs.ee/commit/a2edf1c94812a8459809cdd5e98972c0c6af5214#diff-bc9085f37b09738f4e48e7f926c54c428dd7423ce18cdd8d467045e9333f021cR26

**Comment by chrisguindon** [comment] 2024-10-16 13:49
That did not work.

I've asked @autumnfound to clear the cache folder incase our cache may be corrupted.

**Comment by chrisguindon** [comment] 2024-10-16 13:57
> I’ve asked @autumnfound to clear the cache folder, as there’s a chance the cache might be corrupted.

That didn't help either. I rebuilt the site and I still see all of Francesco's blog posts.

**Comment by fmarchioni** [comment] 2024-10-16 14:47
Hi Chris, all
sorry for the late reply. I just restored the site's top menu which allows extracting the feed also from:
https://www.mastertheboss.com/category/java-ee/jakarta-ee/feed/
hopefully that can help to sort out the issue
regards

**Comment by autumnfound** [comment] 2024-10-16 15:09
> Hi Chris, all sorry for the late reply. I just restored the site's top menu which allows extracting the feed also from: https://www.mastertheboss.com/category/java-ee/jakarta-ee/feed/ hopefully that can help to sort out the issue regards

This should fix the problem, yeah! Looking into the source and fiddling around, I was able to determine that the new_feed_items works on the "id" of feed items, which is generated from the link of the feed. In the case of the 108,110 feed, this was empty but not throwing errors from Venus. This lead to some really inconsistent results on what was in the ID if there was anything, and resulted in no limiting of feed items.

The feed you just posted works, as I've confirmed it locally. I'll make a patch to push the new feed

**Closed** 2024-10-16 16:01 UTC
Labels: bug

**Comment by chrisguindon** [comment] 2024-10-16 16:09
@fmarchioni Thanks so much for getting back to us! With your help, we were finally able to solve this mystery :)

The issue is now fixed in production. A big thanks to @autumnfound for reviewing the source code as we now have a better understanding of how this type of problem can occur and how to address it. 

Moving forward, we should validate RSS feeds before accepting them in jakartablogs.ee to avoid these types of issues.

/cc @oliviergoulet5 @ivargrimstad
